
# # to get the data from mongo db
# GET http://localhost:3000/ HTTP/1.1

# # to insert data in mongo db
POST http://localhost:3000/res HTTP/1.1
Content-Type: application/json

{
    "name":"raju"
}

# # to upate the data 
# PUT http://localhost:3000/res/61a0f104b02659f66c19dccf HTTP/1.1
# Content-Type:: application/json

# {
#     "name":"arya"
# }


# to delete the data 
# DELETE http://localhost:3000/res/61a0fe0beb3dd6cb5adf9fe5 HTTP/1.1